import type { Meta, Row } from './types'

const HEADER = '<!-- GENERATED by cartograph — DO NOT EDIT BY HAND. Regenerate with `cartograph`. -->'

/**
 * The DETERMINISTIC output as `Map<relPath, content>`, rooted at `meta.out`.
 * These files — and ONLY these — are what `--check` gates on. The DeepWiki
 * augment is deliberately NOT here (its LLM prose varies per run and would make
 * a drift gate fail every time); it renders to a separate `WIKI.md` via
 * {@link renderWiki}, which `--check` never inspects.
 */
export function buildFiles(rows: Row[], meta: Meta): Map<string, string> {
  const out = meta.out ?? 'docs'
  const files = new Map<string, string>()
  files.set(`${out}/CODEMAP.md`, renderCodemap(rows, meta))
  files.set(`${out}/codemap.json`, renderJson(rows, meta))
  for (const row of rows) files.set(`${out}/api/${row.entry.apiName}.md`, renderApiPage(row))
  return files
}

/** The non-deterministic DeepWiki artifact `{ path, content }`, or null. */
export function renderWiki(meta: Meta): { path: string; content: string } | null {
  if (!meta.deepwiki) return null
  const out = meta.out ?? 'docs'
  const lines = [
    HEADER.replace(
      'DO NOT EDIT BY HAND. Regenerate with `cartograph`.',
      'AI-GENERATED via DeepWiki — non-authoritative, regenerated with `cartograph --deepwiki`.',
    ),
    '',
    `# ${meta.title} — architecture (DeepWiki)`,
    '',
    `> AI-generated by [DeepWiki](https://deepwiki.com/${meta.slug}); a reading aid, **not** a contract. The source of truth is [\`CODEMAP.md\`](./CODEMAP.md), extracted from source.`,
    '',
  ]
  if (meta.deepwiki.structure) lines.push('## Wiki pages', '', '```', meta.deepwiki.structure.trim(), '```', '')
  for (const { q, a } of meta.deepwiki.answers ?? []) lines.push(`## ${q}`, '', a.trim(), '')
  return { path: `${out}/WIKI.md`, content: `${lines.join('\n').trimEnd()}\n` }
}

function renderCodemap(rows: Row[], meta: Meta): string {
  const title = meta.title ?? 'code map'
  const lines = [HEADER, '', `# ${title} code map`, '']
  lines.push(`_${rows.length} entr${rows.length === 1 ? 'y' : 'ies'} — ${meta.sourceLabel}. Regenerate with \`cartograph\`._`, '')
  lines.push('| Entry | Exports | Depends on |', '|---|---|---|')
  for (const { entry, exports, error, deps } of rows) {
    const link = `[\`${entry.exportPath}\`](api/${entry.apiName}.md)`
    const count = error ? '—' : String(exports.length)
    const dep = deps.length ? deps.map((d) => `\`${d}\``).join(', ') : '—'
    lines.push(`| ${link} | ${count} | ${dep} |`)
  }
  lines.push('', '---', '')
  for (const { entry, exports, error, deps } of rows) {
    lines.push(`## \`${entry.exportPath}\``, '')
    lines.push(`Source: \`${entry.rel}\` · ${error ? 'introspection failed' : `${exports.length} exports`}`, '')
    if (deps.length) lines.push(`Depends on: ${deps.map((d) => `\`${d}\``).join(', ')}`, '')
    if (error) lines.push(`> Could not introspect: ${error}`, '')
    else if (exports.length) lines.push(exports.map((e) => `\`${e.name}\``).join(', '), '', `[Full API →](api/${entry.apiName}.md)`, '')
    else lines.push('_No public exports._', '')
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function renderApiPage({ entry, exports, error }: Row): string {
  const lines = [HEADER, '', `# \`${entry.exportPath}\``, '', `Source: \`${entry.rel}\``, '']
  if (error) return `${[...lines, `> Could not introspect this entry: ${error}`].join('\n').trimEnd()}\n`
  lines.push(`${exports.length} export${exports.length === 1 ? '' : 's'}.`, '')
  for (const e of exports) {
    lines.push(`### \`${e.name}\``, '')
    lines.push(`\`${e.kind}\`${e.doc ? ` — ${e.doc}` : ''}`, '')
    lines.push('```ts', e.signature, '```', '')
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function renderJson(rows: Row[], meta: Meta): string {
  const payload = {
    generator: 'cartograph',
    title: meta.title,
    source: meta.sourceLabel,
    slug: meta.slug ?? null,
    entries: rows.map(({ entry, exports, error, deps }) => ({
      id: entry.exportPath,
      source: entry.rel,
      dependsOn: deps,
      error: error ?? null,
      exports: exports.map((e) => ({ name: e.name, kind: e.kind, signature: e.signature, doc: e.doc || null })),
    })),
  }
  return `${JSON.stringify(payload, null, 2)}\n`
}
